### ISSUE TITLE
`docker run` produces confusing output

### ISSUE THREAD

**Issue by DmitryKey** [o19s/hello-nlp#19]
Hi!
I'm not sure if there is something wrong in my config, but here what I get when running the docker command below:
```
Dmitrys-MacBook-Pro:hello-nlp dmitrykan$ docker run -p 5055:5055 hello_nlp
INFO:     Loading environment from '/app/docker-elasticsearch.conf'
INFO:     Uvicorn running on http://0.0.0.0:5055 (Press CTRL+C to quit)
INFO:     Started parent process [1]
/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
  0%|          | 0.00/245M [00:00<?, ?B/s]/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
 49%|████▊     | 119M/245M [02:20<00:54, 2.29MB/s] 
INFO:     Started server process [8]
INFO:uvicorn.error:Started server process [8]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
100%|█████████▉| 245M/245M [03:22<00:00, 1.89MB/s]{'nlp': <spacy.lang.en.English object at 0x7ff3b2f26a90>, 'stages': ['html_strip', 'tokenize', 'payload'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'payload': True}
{'nlp': <spacy.lang.en.English object at 0x7ff3b2f26a90>, 'stages': ['html_strip', 'tokenize', 'entitize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'entitize': True}
{'nlp': <spacy.lang.en.English object at 0x7ff3b2f26a90>, 'stages': ['html_strip', 'tokenize', 'lemmatize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'lemmatize': True}
{'nlp': <spacy.lang.en.English object at 0x7ff3b2f26a90>, 'stages': ['html_strip', 'tokenize', 'prepositionize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'prepositionize': True}
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./hello_nlp/main.py", line 30, in <module>
    pipelines = Pipelines(config_json)
  File "./hello_nlp/pipeline.py", line 262, in __init__
    self.add_analyzer(analyzer)
  File "./hello_nlp/pipeline.py", line 229, in add_analyzer
    self.analyzers[analyzer["name"]] = Analyzer(analyzer["pipeline"],self.nlp)
  File "./hello_nlp/pipeline.py", line 62, in __init__
    self.stages.append(pipelines[stage](self.metadata))
  File "./plugins/vectorize/__init__.py", line 35, in __init__
    self.model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')
  File "/usr/local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 92, in __init__
    raise e
  File "/usr/local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 72, in __init__
    http_get(model_url, zip_save_path)
  File "/usr/local/lib/python3.7/site-packages/sentence_transformers/util.py", line 211, in http_get
    os.rename(download_filepath, path)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/sentence_transformers/sbert.net_models_distilbert-base-nli-stsb-mean-tokens_part/model.zip_part' -> '/root/.cache/torch/sentence_transformers/sbert.net_models_distilbert-base-nli-stsb-mean-tokens_part/model.zip'
100%|██████████| 245M/245M [03:22<00:00, 1.21MB/s]
```

**Comment by binarymax** [comment]
Yes, I also get this issue.  Seems to be related to the base Docker image and CUDA.

**Comment by binarymax** [comment]
@DmitryKey I am guessing you are using a Mac and don't have a CUDA compatible card in your system?  That is why it's not working for me in Docker...runs fine in a non-docker conda or venv scenario.

**Comment by DmitryKey** [comment]
@binarymax correct, I don't have a card, will try conda/venv. Will check the venv route.
btw, maybe this could be a setting in the docker config?

**Comment by binarymax** [comment]
Yes already working on it since yesterday.  Created a branch docker-cuda.   I can easily tell sbert to use CPU but I can’t figure out how to prevent torch from downloading nvidia drivers, which is a pain.

Another problem is that sbert is reporting the model doesn’t exist in docker either - but when I check the path the file is there...so when I solve the cuda issue I’ll move on to that.

Hope to have it all sorted out early this week!  Thanks so much for testing.

**Comment by DmitryKey** [comment]
thanks @binarymax ! Btw, are you using https://github.com/UKPLab/sentence-transformers for SBERT part?

I have just realized that my default Python is of 2.7 version and it is explicitly mentioned "We recommend Python 3.6 or higher, PyTorch 1.6.0 or higher and transformers v3.1.0 or higher. The code does not work with Python 2.7." in the repo above. But that should not be an issue, since Dockerfile uses python3.7.

**Comment by DmitryKey** [comment]
@binarymax I took the venv path, on start getting this:

     ./run-elastic.sh 
    raise IOError(Errors.E050.format(name=name))
    OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

do you know, why it would complain about model 'en_core_web_sm'? Following the README I've downloaded 'en_core_web_lg'.

**Comment by binarymax** [comment]
Oh oops - change the model in config.json ...I had it set to small for testing and forgot to change it back.

**Comment by DmitryKey** [comment]
thanks @binarymax It launched without errors. One improvement idea: to add an INFO log explaining the download task:

```
(venv) Dmitrys-MacBook-Pro:hello-nlp dmitrykan$ ./run-elastic.sh 
INFO:     Loading environment from 'elasticsearch.conf'
INFO:     Uvicorn running on http://localhost:5055 (Press CTRL+C to quit)
INFO:     Started reloader process [57039] using statreload
{'nlp': <spacy.lang.en.English object at 0x11ea74110>, 'stages': ['html_strip', 'tokenize', 'payload'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'payload': True}
{'nlp': <spacy.lang.en.English object at 0x11ea74110>, 'stages': ['html_strip', 'tokenize', 'entitize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'entitize': True}
{'nlp': <spacy.lang.en.English object at 0x11ea74110>, 'stages': ['html_strip', 'tokenize', 'lemmatize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'lemmatize': True}
{'nlp': <spacy.lang.en.English object at 0x11ea74110>, 'stages': ['html_strip', 'tokenize', 'prepositionize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'prepositionize': True}
100%|████████████████████████████████████████| 245M/245M [02:49<00:00, 1.44MB/s]
{'nlp': <spacy.lang.en.English object at 0x11ea74110>, 'stages': ['html_strip', 'tokenize', 'vectorize'], 'html_strip': True, 'html_parser': 'lxml', 'tokenize': True, 'vectorize': True}
INFO:     Started server process [57041]
INFO:uvicorn.error:Started server process [57041]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
```

**Comment by binarymax** [comment]
Yeah that’s done by SBERT the first time you run it.  I’d need to fork their download lib to get it to show up as an INFO task.

**Comment by binarymax** [comment]
Really glad you got it running!  As you noticed it’s not quite 1.0 yet and the documentation needs a lot of work.  Specifically the field types and schema changes that will accept the output from the field analyzers.  There is a schema example here that has all the mappings you’ll need for the example pipelines: https://github.com/o19s/skipchunk/blob/master/elastic_home/configsets/skipchunk-index-configset/skipchunk-index-schema.json

**Comment by binarymax** [comment]
Also I think you’re the first official person to get it running other than OSC, so thanks a lot for all your help!

**Comment by DmitryKey** [comment]
I'm glad to contribute! I've started making notes in the README fork, so will share as it progresses.
I wasn't sure where to start, and decided to run some scripts in the example/, in particular `index-one.sh` (taking the Elasticsearch route for starters).

The following one-liner returns some response (with vector information):
```bash
curl --header "Content-Type: application/json" \
  --request POST \
  --data @blog-posts-one.json \
  http://localhost:5055/enrich/osc-blog
```

But this one fails:
```bash
curl --header "Content-Type: application/json" \
  --request POST \
  --data @blog-posts-one.json \
  http://localhost:5055/index/osc-blog
```

Not sure why? Then I tried to reindex:
```bash
curl --header "Content-Type: application/json"   --request POST   http://localhost:5055/reindex/osc-blog
```

But I get `{"error":{}}` and in the logs seeing this:

```bash
('NETWORK ERROR! Could not connect to Elasticsearch server on', 'http://localhost:9200/', ' ... Have a nice day.')
INFO:     127.0.0.1:54416 - "POST /reindex/osc-blog HTTP/1.1" 200 OK
```

The CORS is on and configured like so (elasticsearch 7.10.1):

```yml
# CORS
http.cors.allow-origin: "/https?:\\/\\/(.*?\\.)?(quepid\\.com|splainer\\.io)|localhost/"
http.cors.enabled: true

```

**Comment by binarymax** [comment]
I finally figured out the root of the problem, and issued a patch - that also has some fancy CUDA switches too.  Documentation to follow: https://github.com/o19s/hello-nlp/pull/21

**Comment by binarymax** [comment]
@DmitryKey in the effort of granularity I'll make a new issue with your index error that you are getting :)
